### ISSUE TITLE
Add all NDVI regions

### ISSUE THREAD

**Issue by turnerm** [OCHA-DAP/ocha-anticipy#186]
Missing some regions from [here](https://edcintl.cr.usgs.gov/downloads/sciweb1/shared/fews/web/), including South America for Colombia. Some further question:
- Haiti seems to have its [own region](https://edcintl.cr.usgs.gov/downloads/sciweb1/shared/fews/web/lac/camcar/caribbean/hispaniola/haiti/)
- For Colombia not sure if we should choose Colombia or Colombia-Venezuela [see here](https://edcintl.cr.usgs.gov/downloads/sciweb1/shared/fews/web/lac/southamerica/)

**Comment by caldwellst** [comment]
So, had to go through and double check as I can't remember why we had the specific regions we did!

The sources aren't included because they don't actually have NDVI data. If you click through to those regions, you will see that they either don't have dekadal data at all and don't have NDVI. The only exceptions are some of the Middle East countries that have some graphics `.png` files for a couple dekad snapshots a few years ago, but no long history of NDVI data and nothing machine readable.

Re:Haiti, it does seem to have its own region but since it's covered by the Hispaniola data, I didn't think there was a need to specifically cover that as well. I only did for Yemen, for instance, when we didn't have an alternative region-wide coverage (it's the only country available).

Closing, but feel free to re-open if you disagree!
