### ISSUE TITLE
Add ocha-anticipy to conda-forge

### ISSUE THREAD

**Issue by castledan** [OCHA-DAP/ocha-anticipy#96]
Installing GeoPandas with pip on Windows is quite cumbersome, as GDAL and Fiona needs to be manually downloaded and installed. Therefore the installation of the aa-toolbox as it is at the moment doesn't work on Windows. Moreover, other widespread geo-spatial libraries (e.g. Cartopy) are not well supported by pip. Both issues can be solved by using conda, a powerful package manager, which is becoming increasingly popular in the Python community. One great thing about conda is that it also allows to install libraries using pip.

Therefore I think we should add the possibility of installing the toolbox using conda.

**Comment by turnerm** [comment]
To get aa-toolbox on conda-forge, we need to ensure that all its dependencies are also available on conda-forge. 

@kynan is very kindly tackling this, namely getting [hdx-python-country](https://github.com/OCHA-DAP/hdx-python-country/issues/14) and [hdx-python-api](https://github.com/OCHA-DAP/hdx-python-api/issues/38) on to conda forge, which is turning out to be quite complex. 

This issue is also blocked  #140.

**Comment by kynan** [comment]
Dependencies:
* [x] geopandas
* [ ] hdx-python-api>=5.6.4 (OCHA-DAP/hdx-python-api#38)
* [ ] hdx-python-country (OCHA-DAP/hdx-python-country#14)
* [x] numpy
* [x] pydantic
* [x] pyyaml
* [x] requests
* [x] rasterio>=1.3a4;python_version=='3.10'
* [x] rioxarray
* [x] typing-extensions
* [x] wrapt
* [x] xarray[parallel]
  * [x] dask[complete] (provided by [dask conda-forge package](https://github.com/conda-forge/dask-feedstock))

**Comment by kynan** [comment]
@turnerm how are you getting on with this?

**Comment by turnerm** [comment]
@kynan at the usual snail's pace but just made [this PR](https://github.com/conda-forge/staged-recipes/pull/22262) yesterday :)

**Comment by turnerm** [comment]
Done - huge thanks to @kynan!
